---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-order-management
  labels:
    app: user-order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-order-management
  template:
    metadata:
      labels:
        app: user-order-management
    spec:
      containers:
        - name: user-order-management
          image: username/user-order-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-management
  labels:
    app: rider-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-management
  template:
    metadata:
      labels:
        app: rider-management
    spec:
      containers:
        - name: rider-management
          image: username/rider-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-management
  labels:
    app: store-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-management
  template:
    metadata:
      labels:
        app: store-management
    spec:
      containers:
        - name: store-management
          image: username/store-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-order-management
  labels:
    app: user-order-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-order-management


---


apiVersion: v1
kind: Service
metadata:
  name: rider-management
  labels:
    app: rider-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rider-management


---


apiVersion: v1
kind: Service
metadata:
  name: store-management
  labels:
    app: store-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: store-management

